// Author
const ADD_AUTHOR = 'ADD_AUTHOR';
const REMOVE_AUTHOR = 'REMOVE_AUTHOR';
const EDIT_AUTHOR = 'EDIT_AUTHOR';

// Book
const ADD_BOOK = 'ADD_BOOK';
const REMOVE_BOOK = 'REMOVE_BOOK';
const EDIT_BOOK = 'EDIT_BOOK';

//Gerge
const ADD_GERGE = 'ADD_GERGE';
const REMOVE_GERGE = 'REMOVE_GERGE';
const EDIT_GERGE = 'EDIT_GERGE';

module.exports = { ADD_AUTHOR, REMOVE_AUTHOR, EDIT_AUTHOR, ADD_BOOK, EDIT_BOOK, REMOVE_BOOK, ADD_GERGE, REMOVE_GERGE, EDIT_GERGE }