// Author
const ADD_AUTHOR = 'ADDED_AUTHOR';
const REMOVE_AUTHOR = 'REMOVED_AUTHOR';
const EDIT_AUTHOR = 'EDITED_AUTHOR';
const INITIAL_AUTHORS = 'INITIAL_AUTHORS';

// Book
const ADD_BOOK = 'ADDED_BOOK';
const REMOVE_BOOK = 'REMOVED_BOOK';
const EDIT_BOOK = 'EDITED_BOOK';
const INITIAL_BOOKS = 'INITIAL_BOOKS';


//Gerge
const ADD_GERGE = 'ADDED_GERGE';
const REMOVE_GERGE = 'REMOVED_GERGE';
const EDIT_GERGE = 'EDITED_GERGE';
const INITIAL_GERGES = 'INITIAL_GERGES';

module.exports = { ADD_AUTHOR, REMOVE_AUTHOR, EDIT_AUTHOR, INITIAL_AUTHORS, ADD_BOOK, EDIT_BOOK, REMOVE_BOOK, INITIAL_BOOKS, ADD_GERGE, REMOVE_GERGE, EDIT_GERGE, INITIAL_GERGES }